import "@/styles/reset.css"
import "@/styles/global.css"
import { Inter } from 'next/font/google'
import Header from "@/components/Header"
import Footer from "@/components/Footer"

export const metadata = {
  title: 'HERFILMS',
  description: 'Generated by create next app',

}



const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
